//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Troye_Computer_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int empNumber { get; set; }
        public string empName { get; set; }
        public string empSurname { get; set; }
        public Nullable<int> empAge { get; set; }
        public string empHomeNumber { get; set; }
        public string empAddress { get; set; }
        public string empEmail { get; set; }
        public string empCellNumber { get; set; }
        public string ImageIconUrl { get; set; }
    }
}
